const D=window.NIHONGO_DATA, DAY=86400000, $=id=>document.getElementById(id);
const settings=Object.assign({goal:20,newLimit:8,showRomaji:true},JSON.parse(localStorage.getItem('rn_final_settings')||localStorage.getItem('rn22_settings')||'{}'));
let progress=JSON.parse(localStorage.getItem('rn_final_progress')||localStorage.getItem('rn22_progress')||'{}');
let stats=Object.assign({reviews:0,streak:0,lastDay:'',days:{}},JSON.parse(localStorage.getItem('rn_final_stats')||localStorage.getItem('rn22_stats')||'{}'));
let personal=JSON.parse(localStorage.getItem('rn_final_personal')||'[]');
let remoteCourse=JSON.parse(localStorage.getItem('rn_final_remote_course')||'[]');
const baseCards=D.buildCards().filter(c=>['Vokabeln','Kanji','Grammatik','Hiragana','Katakana'].includes(c.deck));
const sentencePack=[
['s1','N5','私は毎朝七時に起きます。','わたしはまいあさしちじにおきます。','I get up at seven every morning.'],['s2','N5','日本語を勉強しています。','にほんごをべんきょうしています。','I am studying Japanese.'],['s3','N5','駅はどこですか。','えきはどこですか。','Where is the station?'],['s4','N5','水をください。','みずをください。','Water, please.'],['s5','N5','明日、友達と映画を見ます。','あした、ともだちとえいがをみます。','Tomorrow I will watch a movie with a friend.'],['s6','N5','この本はとても面白いです。','このほんはとてもおもしろいです。','This book is very interesting.'],['s7','N5','今日は学校へ行きません。','きょうはがっこうへいきません。','I am not going to school today.'],['s8','N5','猫が机の下にいます。','ねこがつくえのしたにいます。','There is a cat under the desk.'],['s9','N5','何時に寝ますか。','なんじにねますか。','What time do you go to bed?'],['s10','N5','一緒に昼ご飯を食べましょう。','いっしょにひるごはんをたべましょう。','Let’s have lunch together.'],
['s11','N4','日本へ行ったことがあります。','にほんへいったことがあります。','I have been to Japan before.'],['s12','N4','音楽を聞きながら勉強します。','おんがくをききながらべんきょうします。','I study while listening to music.'],['s13','N4','雨が降っても行きます。','あめがふってもいきます。','I will go even if it rains.'],['s14','N4','毎日少しずつ読むようにしています。','まいにちすこしずつよむようにしています。','I make sure to read a little every day.'],['s15','N4','宿題をしてからテレビを見ました。','しゅくだいをしてからテレビをみました。','I watched TV after doing my homework.'],['s16','N4','この薬は食事の後で飲んでください。','このくすりはしょくじのあとでのんでください。','Please take this medicine after a meal.'],['s17','N4','もっと早く寝たほうがいいです。','もっとはやくねたほうがいいです。','You should go to bed earlier.'],['s18','N4','来年日本で働くつもりです。','らいねんにほんではたらくつもりです。','I intend to work in Japan next year.'],
['s19','N3','理由をもう少し詳しく説明してください。','りゆうをもうすこしくわしくせつめいしてください。','Please explain the reason in a little more detail.'],['s20','N3','状況によって予定を変更するかもしれません。','じょうきょうによってよていをへんこうするかもしれません。','We may change the plan depending on the situation.'],['s21','N3','この問題についてどう思いますか。','このもんだいについてどうおもいますか。','What do you think about this issue?'],['s22','N3','電車が遅れたため、会議に間に合いませんでした。','でんしゃがおくれたため、かいぎにまにあいませんでした。','Because the train was delayed, I did not make it to the meeting in time.'],['s23','N3','日本に住むようになってから、魚をよく食べます。','にほんにすむようになってから、さかなをよくたべます。','Since I started living in Japan, I eat fish often.'],['s24','N3','彼が来るかどうかまだ分かりません。','かれがくるかどうかまだわかりません。','I still do not know whether he will come.'],['s25','N2','経験を積むにつれて、自分の弱点が見えてきました。','けいけんをつむにつれて、じぶんのじゃくてんがみえてきました。','As I gained experience, I began to see my own weaknesses.'],['s26','N2','結果にかかわらず、最後までやり抜くつもりです。','けっかにかかわらず、さいごまでやりぬくつもりです。','Regardless of the result, I intend to see it through to the end.'],['s27','N2','この制度は若者だけでなく、高齢者にも利用されています。','このせいどはわかものだけでなく、こうれいしゃにもりようされています。','This system is used not only by young people but also by older people.'],['s28','N1','彼の発言は誤解を招きかねない。','かれのはつげんはごかいをまねきかねない。','His remark could easily lead to misunderstanding.'],['s29','N1','状況を把握した上で、最終的な判断を下すべきだ。','じょうきょうをはあくしたうえで、さいしゅうてきなはんだんをくだすべきだ。','A final decision should be made after fully understanding the situation.'],['s30','N1','努力なくして大きな成果は望めない。','どりょくなくしておおきなせいかはのぞめない。','Without effort, one cannot expect major results.']
].map(([id,level,jp,reading,en])=>({id,level,jp,reading,en}));
const grammarEN={'A は B です':'A is B.','～ですか':'polite question form','A の B':'B of A / A’s B','A も B':'A also B','～を + Verb':'marks the direct object','～に':'time / destination / location of existence','～へ':'direction / destination','～で':'place of action / means','～と':'with / and / quotation','～から / ～まで':'from / until','あります / います':'there is / there are','～たいです':'want to do','～てください':'please do','～てもいいです':'may / be allowed to','～てはいけません':'must not','～ませんか':'invitation: won’t you…?','～ましょう':'let’s…','～ながら':'while doing','～と思います':'I think that…','～と思う':'think that…','～なければならない':'must / have to','～たことがある':'have done before','～ようにする':'make sure to / try to','～ことになる':'it is decided / it turns out that','～わけではない':'it is not that…','～に違いない':'must surely be','～ものの':'although','～に伴って':'along with / accompanying','～を皮切りに':'starting with','～に堪えない':'cannot bear / too… to endure','～を余儀なくされる':'be forced to','～と言う':'say that','～たり～たりする':'do things such as…','～なくてもいい':'do not have to','～かもしれない':'might / maybe','～でしょう':'probably / right?','～そうだ（様態）':'looks like / seems','～そうだ（伝聞）':'I hear that…','～ようと思う':'intend to','～予定だ':'be scheduled / planned','～つもりだ':'intend to','～ほうがいい':'had better / should','～すぎる':'too much / excessively','～やすい':'easy to','～にくい':'hard to','～始める':'start doing','～終わる':'finish doing','～続ける':'continue doing','～てみる':'try doing','～ておく':'do in advance','～てしまう':'finish completely / regrettably do','～てある':'has been done intentionally','～ているところだ':'be in the middle of doing','～るところだ':'be just about to do','～たところだ':'have just done','～ようになる':'come to / become','～ので':'because','～のに':'although','～し':'and / besides / because','～なら':'if it is / if we are talking about','～たら':'if / when','～ば':'if','～と':'whenever / when','～ても':'even if','～しか～ない':'only','～でも':'for example / even','～について':'about / concerning','～によると':'according to','～までに':'by / no later than','～間に':'while / during','～前に':'before','～後で':'after / later','～ために':'in order to / for','～方':'way of doing','～かどうか':'whether or not','～ようだ':'it seems / appears'};
const GRAMMAR_LESSONS={
'A は B です':{explain:'Use は to mark the topic and です to make a polite statement. Think: “As for A, it is B.”',example:'私は学生です。',translation:'I am a student.'},
'～ですか':{explain:'Add か to the end of a polite sentence to make a question. The word order normally stays the same.',example:'学生ですか。',translation:'Are you a student?'},
'A の B':{explain:'の links two nouns. A describes, owns, or belongs with B. The second noun is the main noun.',example:'日本の本です。',translation:'It is a Japanese book.'},
'A も B':{explain:'も replaces は or が when you mean “also / too”.',example:'私も学生です。',translation:'I am a student too.'},
'～を + Verb':{explain:'を marks the direct object of an action: the thing you eat, read, watch, buy, and so on.',example:'水を飲みます。',translation:'I drink water.'},
'～に':{explain:'に commonly marks a specific time, a destination, or the place where something exists.',example:'七時に起きます。',translation:'I get up at seven.'},
'～へ':{explain:'へ marks direction toward a destination. As a particle it is pronounced “e”.',example:'日本へ行きます。',translation:'I go to Japan.'},
'～で':{explain:'で marks the place where an action happens, or the means used to do something.',example:'学校で勉強します。',translation:'I study at school.'},
'～と':{explain:'と can mean “with”, join nouns as “and”, or mark quoted speech depending on context.',example:'友達と話します。',translation:'I speak with a friend.'},
'～から / ～まで':{explain:'から marks a starting point (“from”), while まで marks an end point (“until / to”).',example:'九時から五時までです。',translation:'It is from nine until five.'},
'あります / います':{explain:'Use あります for inanimate things and います for people and animals when saying that something exists.',example:'猫がいます。',translation:'There is a cat.'},
'～たいです':{explain:'Attach たい to the verb stem to say that you want to do something.',example:'日本へ行きたいです。',translation:'I want to go to Japan.'},
'～てください':{explain:'Use the て-form + ください for a polite request: “please do …”.',example:'見てください。',translation:'Please look.'},
'～てもいいです':{explain:'Use the て-form + もいいです to say that an action is allowed or to ask permission.',example:'ここで食べてもいいです。',translation:'You may eat here.'},
'～てはいけません':{explain:'Use the て-form + はいけません to say that something must not be done.',example:'ここで写真を撮ってはいけません。',translation:'You must not take photos here.'},
'～ませんか':{explain:'A negative polite question with ませんか is a soft invitation: “Won’t you …?”',example:'一緒に食べませんか。',translation:'Would you like to eat together?'},
'～ましょう':{explain:'Use the verb stem + ましょう to suggest doing something together: “Let’s …”.',example:'一緒に食べましょう。',translation:'Let’s eat together.'},
'～たことがある':{explain:'Past plain form + ことがある expresses past experience: “have done … before”.',example:'日本へ行ったことがあります。',translation:'I have been to Japan before.'},
'～ながら':{explain:'Attach ながら to the verb stem to describe two actions happening at the same time.',example:'音楽を聞きながら勉強します。',translation:'I study while listening to music.'},
'～ても':{explain:'The て-form + も can mean “even if / even though”.',example:'雨が降っても行きます。',translation:'I will go even if it rains.'},
'～ようにする':{explain:'Use ようにする for a deliberate habit or effort: “make sure to / try to …”.',example:'毎日読むようにしています。',translation:'I make sure to read every day.'},
'～ほうがいい':{explain:'Past/plain form + ほうがいい gives advice: “you should / had better …”.',example:'早く寝たほうがいいです。',translation:'You should go to bed early.'},
'～つもりだ':{explain:'Plain form + つもり expresses an intention or plan.',example:'日本で働くつもりです。',translation:'I intend to work in Japan.'},
'～かもしれない':{explain:'Plain form + かもしれない expresses possibility: “might / maybe”.',example:'予定を変更するかもしれません。',translation:'We may change the plan.'},
'～について':{explain:'Noun + について means “about / concerning” and introduces a topic of discussion.',example:'この問題について話します。',translation:'I will talk about this issue.'},
'～ために':{explain:'ために can express purpose (“in order to”) or cause (“because of”), depending on the form before it.',example:'勉強するために図書館へ行きます。',translation:'I go to the library in order to study.'},
'～かどうか':{explain:'Use かどうか after a plain clause to mean “whether or not”.',example:'来るかどうか分かりません。',translation:'I do not know whether he will come.'}
};
const FOUNDATION_WORDS=[
{id:'fv-n5-1',level:'N5',front:'毎朝',reading:'まいあさ · maiasa',meaning:'every morning',deck:'Vokabeln',example:'毎朝七時に起きます。'},
{id:'fv-n5-2',level:'N5',front:'七時',reading:'しちじ · shichiji',meaning:'seven o’clock',deck:'Vokabeln',example:'七時に起きます。'},
{id:'fv-n5-3',level:'N5',front:'勉強する',reading:'べんきょうする · benkyou suru',meaning:'to study',deck:'Vokabeln',example:'日本語を勉強します。'},
{id:'fv-n5-4',level:'N5',front:'映画',reading:'えいが · eiga',meaning:'movie / film',deck:'Vokabeln',example:'映画を見ます。'},
{id:'fv-n5-5',level:'N5',front:'猫',reading:'ねこ · neko',meaning:'cat',deck:'Vokabeln',example:'猫がいます。'},
{id:'fv-n5-6',level:'N5',front:'何時',reading:'なんじ · nanji',meaning:'what time',deck:'Vokabeln',example:'何時に寝ますか。'},
{id:'fv-n5-7',level:'N5',front:'一緒に',reading:'いっしょに · issho ni',meaning:'together',deck:'Vokabeln',example:'一緒に食べましょう。'},
{id:'fv-n5-8',level:'N5',front:'昼ご飯',reading:'ひるごはん · hirugohan',meaning:'lunch',deck:'Vokabeln',example:'昼ご飯を食べます。'}
];
const SENTENCE_RULES={
 s1:{v:['私','毎朝','七時','起きる'],g:['～に']},s2:{v:['日本語','勉強する'],g:['～を + Verb']},s3:{v:['駅','どこ'],g:['～ですか']},s4:{v:['水'],g:['～てください']},s5:{v:['明日','友達','映画','見る'],g:['～と','～を + Verb']},
 s6:{v:['本','面白い'],g:['A は B です']},s7:{v:['今日','学校','行く'],g:['～へ']},s8:{v:['猫','机','下'],g:['あります / います','～に']},s9:{v:['何時','寝る'],g:['～ですか','～に']},s10:{v:['一緒に','昼ご飯','食べる'],g:['～ましょう','～を + Verb']},
 s11:{v:['日本','行く'],g:['～たことがある']},s12:{v:['聞く'],g:['～ながら']},s13:{v:['行く'],g:['～ても']},s14:{v:['読む'],g:['～ようにする']},s15:{v:['見る'],g:[]},s16:{v:['飲む'],g:['～てください']},s17:{v:[],g:['～ほうがいい']},s18:{v:['日本'],g:['～つもりだ']},
 s19:{v:['理由','説明'],g:['～てください']},s20:{v:['状況','予定'],g:['～かもしれない']},s21:{v:[],g:['～について']},s22:{v:[],g:['～ために']},s23:{v:['日本','食べる'],g:['～ようになる']},s24:{v:['来る'],g:['～かどうか']}
};
function lessonInfo(c){return GRAMMAR_LESSONS[c.front]||{explain:`Learn what ${c.front} does, where it appears in a sentence, and how it changes the meaning before you are asked to use it.`,example:c.example||'',translation:grammarEN[c.front]||'grammar pattern'}}
const offlineEN={私:'I / me',あなた:'you',人:'person',日本:'Japan',日本語:'Japanese',先生:'teacher',学生:'student',友達:'friend',家族:'family',水:'water',お茶:'tea',ご飯:'rice / meal',食べる:'to eat',飲む:'to drink',行く:'to go',来る:'to come',見る:'to see / watch',聞く:'to hear / ask',話す:'to speak',読む:'to read',書く:'to write',買う:'to buy',大きい:'big',小さい:'small',新しい:'new',古い:'old',良い:'good',悪い:'bad',今日:'today',明日:'tomorrow',昨日:'yesterday',今:'now',朝:'morning',夜:'night / evening',駅:'station',学校:'school',病院:'hospital',店:'shop',右:'right',左:'left',上:'above / on',下:'below / under',中:'inside',外:'outside',何:'what',誰:'who',ありがとう:'thank you',すみません:'excuse me / sorry',お願いします:'please',大丈夫:'okay / all right',必要:'necessary',予定:'plan / schedule',経験:'experience',説明:'explanation',準備:'preparation',続ける:'to continue',比べる:'to compare',選ぶ:'to choose',状況:'situation',理由:'reason',影響:'influence / effect',方法:'method',関係:'relationship / connection',可能:'possible'};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function remoteCards(){return remoteCourse.map(x=>({id:'r-'+x.id,level:x.level||'N5',front:x.word||x.reading,reading:x.reading,meaning:x.en,deck:'Vokabeln',example:''}))}
function personalCards(){return personal.map(x=>({id:'p-'+x.id,level:x.level||'N5',front:x.word||x.reading,reading:x.reading,meaning:x.en,deck:'Vokabeln',example:x.example||''}))}
function english(c){if(c.deck==='Grammatik')return grammarEN[c.front]||'grammar pattern';if(c.deck==='Hiragana'||c.deck==='Katakana')return c.meaning;if(c.meaning&&/^[\x00-\x7F]/.test(c.meaning))return c.meaning;return offlineEN[c.front]||''}
function allCards(){return [...baseCards,...FOUNDATION_WORDS,...remoteCards(),...personalCards()]}
function key(c,dir){return `${c.id}::${dir}`}
function pf(c,dir){const k=key(c,dir);if(!progress[k])progress[k]={reps:0,due:0,interval:0,ease:2.35,again:0,hard:0,good:0,easy:0};return progress[k]}
function save(){localStorage.setItem('rn_final_settings',JSON.stringify(settings));localStorage.setItem('rn_final_progress',JSON.stringify(progress));localStorage.setItem('rn_final_stats',JSON.stringify(stats));localStorage.setItem('rn_final_personal',JSON.stringify(personal));localStorage.setItem('rn_final_remote_course',JSON.stringify(remoteCourse))}
function eligible(){return allCards().filter(c=>['N5','N4','N3','N2','N1','Kana'].includes(c.level)&&((c.deck==='Hiragana'||c.deck==='Katakana')||english(c)||c.deck==='Grammatik'))}
function score(p){return !p||!p.reps?0:Math.max(0,(p.good||0)+(p.easy||0)-(p.again||0)*.5-(p.hard||0)*.15)}
function receptiveKnown(c){const p=pf(c,'jp-en');return p.reps>=2&&p.interval>=.45&&score(p)>=1}
function receptiveStrong(c){const p=pf(c,'jp-en');return p.reps>=3&&p.interval>=1&&score(p)>=1.8}
function productiveReady(c){return receptiveStrong(c)}
function productiveKnown(c){const p=pf(c,'en-jp');return p.reps>=2&&p.interval>=.35&&score(p)>=.8}
function lessonSeen(c){return !!progress[`lesson::${c.id}`]?.reps}
function grammarKnown(c){return lessonSeen(c)&&pf(c,'jp-en').reps>=2&&score(pf(c,'jp-en'))>=.8}
function cardsAt(level,deck){return eligible().filter(c=>c.level===level&&(!deck||c.deck===deck))}
function ratioKnown(level,deck,fn=receptiveKnown){const a=cardsAt(level,deck);return a.length?a.filter(fn).length/a.length:0}
function activeLevel(){for(const level of ['N5','N4','N3','N2','N1']){const v=cardsAt(level,'Vokabeln').filter(c=>english(c));if(!v.length)continue;if(v.filter(receptiveKnown).length<Math.min(v.length,Math.max(35,Math.ceil(v.length*.65))))return level}return'N1'}
function findWord(word){return eligible().find(c=>c.deck==='Vokabeln'&&c.front===word)}
function findGrammar(pattern){return eligible().find(c=>c.deck==='Grammatik'&&c.front===pattern)}
function sentenceUnlocked(s){const r=SENTENCE_RULES[s.id]||{v:[],g:[]};const words=r.v.map(findWord).filter(Boolean);const grams=r.g.map(findGrammar).filter(Boolean);const vocabOK=words.length?words.every(receptiveKnown):cardsAt(s.level,'Vokabeln').filter(receptiveKnown).length>=12;const grammarOK=grams.length?grams.every(grammarKnown):cardsAt(s.level,'Grammatik').some(grammarKnown);return vocabOK&&grammarOK}
function sentenceProductionUnlocked(s){if(!sentenceUnlocked(s))return false;const c={id:s.id,level:s.level,front:s.jp,reading:s.reading,meaning:s.en,deck:'Sentence'};if(!receptiveStrong(c))return false;const r=SENTENCE_RULES[s.id]||{v:[]};const words=r.v.map(findWord).filter(Boolean);return words.every(productiveKnown)}
function directionUnlocked(c,dir){if(dir==='jp-en')return true;if(c.deck==='Vokabeln'||c.deck==='Kanji')return productiveReady(c);return false}
function directionsFor(c){if(c.deck==='Hiragana'||c.deck==='Katakana'||c.deck==='Grammatik')return ['jp-en'];return ['jp-en','en-jp'].filter(d=>directionUnlocked(c,d))}
function task(c,dir,p=pf(c,dir)){return{kind:c.deck==='Grammatik'?'GRAMMAR PRACTICE':c.deck==='Kanji'?'KANJI':c.deck==='Hiragana'||c.deck==='Katakana'?'KANA':'WORD',c,dir,p}}
function dueTasks(){const now=Date.now(),out=[];for(const c of eligible())for(const d of directionsFor(c)){const p=pf(c,d);if(p.reps&&p.due<=now)out.push(task(c,d,p))}for(const s of sentencePack){const c={id:s.id,level:s.level,front:s.jp,reading:s.reading,meaning:s.en,deck:'Sentence'};for(const d of ['jp-en','en-jp']){if(d==='jp-en'&&!sentenceUnlocked(s))continue;if(d==='en-jp'&&!sentenceProductionUnlocked(s))continue;const p=pf(c,d);if(p.reps&&p.due<=now)out.push({kind:d==='jp-en'?'SENTENCE READING':'SENTENCE PRODUCTION',c,dir:d,p})}}return out.sort((a,b)=>a.p.due-b.p.due)}
function nextGrammarLessons(level,limit=1){const vocabKnown=cardsAt(level,'Vokabeln').filter(receptiveKnown).length;if(vocabKnown<8)return[];return cardsAt(level,'Grammatik').filter(c=>!lessonSeen(c)).slice(0,limit).map(c=>({kind:'GRAMMAR LESSON',c,dir:'lesson',p:{reps:0,due:0,interval:0}}))}
function newTasks(limit=settings.newLimit){const level=activeLevel(),arr=[];const kana=eligible().filter(c=>['Hiragana','Katakana'].includes(c.deck)&&!pf(c,'jp-en').reps);const kanaKnown=eligible().filter(c=>['Hiragana','Katakana'].includes(c.deck)&&receptiveKnown(c)).length;if(kanaKnown<35)for(const c of kana.slice(0,Math.min(limit,6)))arr.push(task(c,'jp-en'));
 const vocab=cardsAt(level,'Vokabeln').filter(c=>english(c));for(const c of vocab){if(!pf(c,'jp-en').reps)arr.push(task(c,'jp-en'));else if(directionUnlocked(c,'en-jp')&&!pf(c,'en-jp').reps)arr.push(task(c,'en-jp'))}
 const kanji=cardsAt(level,'Kanji').filter(c=>english(c));for(const c of kanji)if(!pf(c,'jp-en').reps)arr.push(task(c,'jp-en'));
 const grammar=cardsAt(level,'Grammatik').filter(c=>lessonSeen(c));for(const c of grammar)if(!pf(c,'jp-en').reps)arr.push(task(c,'jp-en'));
 const priority=t=>t.dir==='jp-en'&&t.kind==='WORD'?0:t.kind==='KANA'?1:t.kind==='GRAMMAR PRACTICE'?2:t.kind==='KANJI'?3:t.dir==='en-jp'?5:4;arr.sort((a,b)=>priority(a)-priority(b));return arr.slice(0,limit)}
function sentenceTasks(limit=2){const level=activeLevel(),out=[];for(const s of sentencePack.filter(s=>s.level===level)){const c={id:s.id,level:s.level,front:s.jp,reading:s.reading,meaning:s.en,deck:'Sentence'};if(sentenceUnlocked(s)&&!pf(c,'jp-en').reps)out.push({kind:'SENTENCE READING',c,dir:'jp-en',p:pf(c,'jp-en')});if(sentenceProductionUnlocked(s)&&!pf(c,'en-jp').reps)out.push({kind:'SENTENCE PRODUCTION',c,dir:'en-jp',p:pf(c,'en-jp')})}return out.slice(0,limit)}


async function seedCourseVocabulary(){
  if(!navigator.onLine)return;
  const levels=['N5','N4','N3','N2','N1'];
  // Keep a broad cached course pool without forcing the learner to browse a dictionary.
  // Lower levels are filled first; later levels become available naturally as progress grows.
  const counts=Object.fromEntries(levels.map(l=>[l,remoteCourse.filter(x=>x.level===l).length]));
  let target=levels.find(l=>counts[l]<60)||null;if(!target)return;
  const page=Math.floor(counts[target]/20)+1;
  try{
    const r=await fetch(`https://jisho.org/api/v1/search/words?keyword=${encodeURIComponent('#jlpt-'+target.toLowerCase())}&page=${page}`);
    if(!r.ok)return;const j=await r.json();
    for(const x of (j.data||[])){
      const ja=x.japanese?.[0]||{},defs=(x.senses||[]).flatMap(s=>s.english_definitions||[]).slice(0,5);
      const word=ja.word||ja.reading||x.slug,reading=ja.reading||'';if(!word||!defs.length)continue;
      const id=String(x.slug||word+'-'+reading).replace(/[^\w\u3000-\u9fff-]/g,'_');
      if(!remoteCourse.some(y=>y.id===id))remoteCourse.push({id,level:target,word,reading,en:defs.join('; ')});
    }save();
  }catch(e){}
}
let queue=[],qi=0,current=null;
function buildSession(){const due=dueTasks(),level=activeLevel(),lessons=nextGrammarLessons(level,1),fresh=newTasks(Math.max(0,settings.goal-due.length-lessons.length)),sentences=sentenceTasks(2);queue=[...due.slice(0,settings.goal),...lessons,...fresh,...sentences].slice(0,Math.max(settings.goal,10));if(!queue.length)queue=[...nextGrammarLessons(level,1),...newTasks(5),...sentenceTasks(1)];qi=0}
function showTask(){current=queue[qi];if(!current){finishSession();return}$('answer').classList.add('hidden');$('ratings').classList.add('hidden');$('revealBtn').classList.remove('hidden');const {c,dir,kind}=current,en=kind.startsWith('SENTENCE')?c.meaning:english(c);const lesson=kind==='GRAMMAR LESSON',sentence=kind.startsWith('SENTENCE');$('taskType').textContent=lesson?'GRAMMAR LESSON · NEW':`${kind} · ${dir==='jp-en'?'JAPANESE → ENGLISH':'ENGLISH → JAPANESE'}`;$('taskPrompt').textContent=lesson?'Learn this pattern before you use it in sentences.':kind==='SENTENCE READING'?'Read and understand the whole sentence.':kind==='SENTENCE PRODUCTION'?'Build the Japanese sentence from English.':dir==='jp-en'?'Give the English meaning.':'Recall the Japanese word. You have already learned it in the easier direction.';$('counter').textContent=`${qi+1}/${queue.length}`;$('front').textContent=lesson?c.front:(dir==='jp-en'?c.front:en);$('front').classList.toggle('sentence',sentence);$('reading').textContent=!lesson&&dir==='jp-en'&&settings.showRomaji?(c.reading||''):'';$('hint').textContent=lesson?'No test yet — understand the rule and example first.':kind==='SENTENCE READING'?'Every key word and grammar pattern in this sentence has already been introduced.':kind==='SENTENCE PRODUCTION'?'Advanced recall: this appears only after the words and sentence are already familiar.':dir==='en-jp'?'Active recall is harder, so it unlocks only after recognition is stable.':'Think first, then reveal.';$('meaning').textContent=lesson?(grammarEN[c.front]||'Grammar pattern'):(dir==='jp-en'?en:c.front);if(lesson){const li=lessonInfo(c);$('example').textContent=li.explain;$('exampleEn').textContent=[li.example,li.translation].filter(Boolean).join('  ·  ')}else{$('example').textContent=(c.example&&!sentence)?c.example:'';$('exampleEn').textContent=''}const input=$('taskInput');input.value='';input.classList.toggle('hidden',dir!=='en-jp');input.placeholder=kind==='SENTENCE PRODUCTION'?'Type the Japanese sentence (optional)':'Type Japanese (optional)';$('revealBtn').textContent=lesson?'Show lesson':'Show answer'}
function reveal(){$('answer').classList.remove('hidden');$('ratings').classList.remove('hidden');$('revealBtn').classList.add('hidden');updateTimes()}
function grade(g){if(current.kind==='GRAMMAR LESSON'){const k=`lesson::${current.c.id}`;const p=progress[k]||{reps:0};p.reps++;p.last=Date.now();p.understanding=g;progress[k]=p;stats.reviews++;touchDay();save();qi++;showTask();renderHome();return}const p=pf(current.c,current.dir);p.reps++;p[g]=(p[g]||0)+1;if(g==='again'){p.interval=current.dir==='en-jp'?.006:.012;p.ease=Math.max(1.3,p.ease-.18)}else if(g==='hard'){p.interval=Math.max(.08,(p.interval||.05)*1.35);p.ease=Math.max(1.3,p.ease-.05)}else if(g==='good'){p.interval=p.reps<2?.5:Math.max(1,(p.interval||.5)*p.ease)}else{p.interval=p.reps<2?1.5:Math.max(3,(p.interval||1)*p.ease*1.35);p.ease=Math.min(3,p.ease+.08)}if(current.dir==='en-jp')p.interval*=.68;p.due=Date.now()+p.interval*DAY;stats.reviews++;touchDay();save();qi++;showTask();renderHome()}
function touchDay(){const d=new Date().toISOString().slice(0,10);stats.days[d]=(stats.days[d]||0)+1;if(stats.lastDay!==d){const y=new Date(Date.now()-DAY).toISOString().slice(0,10);stats.streak=stats.lastDay===y?stats.streak+1:1;stats.lastDay=d}}
function fmt(days){if(days<.03)return `${Math.max(1,Math.round(days*1440))}m`;if(days<1)return `${Math.round(days*24)}h`;return `${Math.round(days)}d`}
function updateTimes(){if(current.kind==='GRAMMAR LESSON'){$('againTime').textContent='review';$('hardTime').textContent='soon';$('goodTime').textContent='learned';$('easyTime').textContent='clear';return}const p=pf(current.c,current.dir),m=current.dir==='en-jp'?.68:1;$('againTime').textContent=fmt(.012*m);$('hardTime').textContent=fmt(Math.max(.08,(p.interval||.05)*1.35)*m);$('goodTime').textContent=fmt((p.reps<1?.5:Math.max(1,(p.interval||.5)*p.ease))*m);$('easyTime').textContent=fmt((p.reps<1?1.5:Math.max(3,(p.interval||1)*p.ease*1.35))*m)}
function renderHome(){const due=dueTasks().length,n=newTasks(settings.newLimit).length,level=activeLevel(),day=new Date().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'});$('todayLabel').textContent=day.toUpperCase();$('dueText').textContent=`${due} review${due===1?'':'s'}`;$('newText').textContent=`${n} new`;$('streakText').textContent=`${stats.streak} day streak`;$('goalText').textContent=`${settings.goal} cards goal`;$('todayCards').innerHTML=`<div class="mini"><strong>${due}</strong><span>due now</span></div><div class="mini"><strong>${n}</strong><span>new ready</span></div><div class="mini"><strong>${stats.reviews}</strong><span>total reviews</span></div>`;const vr=Math.round(ratioKnown(level,'Vokabeln')*100),gr=Math.round(ratioKnown(level,'Grammatik',grammarKnown)*100);const sentenceReady=sentencePack.filter(s=>s.level===level&&sentenceUnlocked(s)).length;$('heroTitle').textContent=due?'Reviews first.':`Next: ${level} foundations.`;$('heroText').textContent=vr<25?'Build vocabulary first. Grammar and sentences unlock when you are ready.':gr<20?'Vocabulary is growing. Grammar lessons are now entering your sessions.':'Your course mixes reviews, vocabulary, grammar and unlocked sentences automatically.';$('courseCard').innerHTML=`<strong>${level} · Understand first, produce later</strong><p>1. Vocabulary recognition → 2. Grammar lesson → 3. Sentence reading → 4. Word production → 5. Sentence production.</p><div class="bar"><i style="width:${Math.min(100,Math.round(vr*.65+gr*.35))}%"></i></div><p>${vr}% vocabulary foundation · ${gr}% grammar foundation · ${sentenceReady} sentence${sentenceReady===1?'':'s'} unlocked</p>`}
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='progress')renderProgress()}
function renderProgress(){const ps=Object.entries(progress),learned=ps.filter(([,p])=>p.reps).length,mastered=ps.filter(([,p])=>p.interval>=21).length;$('progressGrid').innerHTML=`<div class="panel"><strong>${stats.reviews}</strong><span class="subtle">reviews</span></div><div class="panel"><strong>${learned}</strong><span class="subtle">directions learned</span></div><div class="panel"><strong>${mastered}</strong><span class="subtle">long-term</span></div><div class="panel"><strong>${stats.streak}</strong><span class="subtle">day streak</span></div>`;let jp=0,en=0,jpc=0,enc=0;for(const[k,p]of ps){if(k.endsWith('::jp-en')){jp+=(p.again||0)+(p.hard||0);jpc+=p.reps||0}else if(k.endsWith('::en-jp')){en+=(p.again||0)+(p.hard||0);enc+=p.reps||0}}$('directionStats').innerHTML=`<div class="directionRow"><span>Japanese → English</span><strong>${jpc?Math.round(100*jp/jpc):0}% difficult</strong></div><div class="directionRow"><span>English → Japanese</span><strong>${enc?Math.round(100*en/enc):0}% difficult</strong></div>`}
async function dictSearch(){const q=$('dictSearch').value.trim();if(!q)return;const out=$('dictResults');out.innerHTML='<p class="subtle">Searching the Japanese dictionary…</p>';const local=allCards().filter(c=>[c.front,c.reading,english(c)].join(' ').toLowerCase().includes(q.toLowerCase())).slice(0,8);let remote=[];try{const r=await fetch('https://jisho.org/api/v1/search/words?keyword='+encodeURIComponent(q));if(!r.ok)throw Error();const j=await r.json();remote=(j.data||[]).slice(0,20).map((x,i)=>{const ja=x.japanese?.[0]||{},defs=(x.senses||[]).flatMap(s=>s.english_definitions||[]).slice(0,6);return{id:x.slug||`${Date.now()}-${i}`,word:ja.word||ja.reading||x.slug,reading:ja.reading||'',en:defs.join('; '),common:!!x.is_common,jlpt:(x.jlpt||[]).join(', ')}});$('dictStatus').innerHTML='<span class="connectionDot"></span>Online JMdict/Jisho search active'}catch(e){$('dictStatus').innerHTML='<span class="connectionDot off"></span>Offline — showing saved/course entries only'}
const merged=[];for(const c of local)merged.push({id:c.id,word:c.front,reading:c.reading||'',en:english(c),local:true});for(const r of remote)if(!merged.some(x=>x.word===r.word&&x.reading===r.reading))merged.push(r);if(!merged.length){out.innerHTML='<div class="dictItem"><b>No result.</b></div>';return}out.innerHTML=merged.map(x=>`<div class="dictItem"><div class="jp">${esc(x.word)}</div><div class="rd">${esc(x.reading)}</div><div class="en">${esc(x.en||'')}</div><div class="dictMeta">${x.common?'Common · ':''}${esc(x.jlpt||'')}</div>${x.local?'':`<div class="dictActions"><button class="smallBtn" data-add="${esc(x.id)}">Add to learning</button></div>`}</div>`).join('');out.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const x=remote.find(r=>String(r.id)===b.dataset.add);if(!x)return;if(!personal.some(p=>p.word===x.word&&p.reading===x.reading)){personal.push({...x,level:(x.jlpt.match(/n[1-5]/i)?.[0]||'N5').toUpperCase()});save();renderHome()}b.textContent='Added ✓';b.disabled=true})}
function finishSession(){toast('Session complete');screen('home');renderHome()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1400)}
$('continueBtn').onclick=async()=>{$('continueBtn').disabled=true;$('continueBtn').innerHTML='Preparing…';await seedCourseVocabulary();buildSession();screen('learn');showTask();$('continueBtn').disabled=false;$('continueBtn').innerHTML='Continue <span>→</span>'};$('closeLearn').onclick=()=>screen('home');$('revealBtn').onclick=reveal;$('ratings').onclick=e=>{const b=e.target.closest('button[data-g]');if(b)grade(b.dataset.g)};document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>screen(b.dataset.screen));$('settingsBtn').onclick=()=>screen('settings');$('closeSettings').onclick=()=>screen('home');$('dictBtn').onclick=dictSearch;$('dictSearch').addEventListener('keydown',e=>{if(e.key==='Enter')dictSearch()});$('goalInput').value=settings.goal;$('newInput').value=settings.newLimit;$('romajiToggle').checked=settings.showRomaji;$('goalInput').onchange=e=>{settings.goal=+e.target.value;save();renderHome()};$('newInput').onchange=e=>{settings.newLimit=+e.target.value;save();renderHome()};$('romajiToggle').onchange=e=>{settings.showRomaji=e.target.checked;save()};$('resetBtn').onclick=()=>{if(confirm('Reset all learning progress?')){progress={};stats={reviews:0,streak:0,lastDay:'',days:{}};save();renderHome();toast('Progress reset')}};window.addEventListener('online',()=>{$('dictStatus').innerHTML='<span class="connectionDot"></span>Online dictionary ready'});window.addEventListener('offline',()=>{$('dictStatus').innerHTML='<span class="connectionDot off"></span>Offline — saved/course entries available'});if(!navigator.onLine)$('dictStatus').innerHTML='<span class="connectionDot off"></span>Offline — saved/course entries available';renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
